[build]
  publish = "dist/"
  command = "npm run dev"

[context.development]
  command = "BASE_URL=$URL npm run dev"

[context.deploy-preview]
  command = "BASE_URL=$DEPLOY_PRIME_URL npm run dev"

[context.branch-deploy]
  command = "BASE_URL=$DEPLOY_URL npm run dev"
